<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GuardRail.Hardware.GuardRailCustom\GuardRail.Hardware.GuardRailCustom.csproj" />
  </ItemGroup>

</Project>
