<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UserSecretsId>dotnet-GuardRail.Local.Service-fa371ff2-f04a-4e9f-94ca-131e0981296d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GuardRail.Api.Models\GuardRail.Api.Models.csproj" />
    <ProjectReference Include="..\GuardRail.Api\GuardRail.Api.csproj" />
    <ProjectReference Include="..\SupportedHardware\GuardRailCustom\GuardRail.Hardware.GuardRailCustom\GuardRail.Hardware.GuardRailCustom.csproj" />
  </ItemGroup>
</Project>