<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>GuardRail.Mobile.Client</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>GuardRail Mobile</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.g3software.guardrail.mobile.client</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\arrow_down.svg" />
	  <None Remove="Resources\Images\close.svg" />
	  <None Remove="Resources\Images\facebook.svg" />
	  <None Remove="Resources\Images\gear.svg" />
	  <None Remove="Resources\Images\google.svg" />
	  <None Remove="Resources\Images\list.svg" />
	  <None Remove="Resources\Images\location.svg" />
	  <None Remove="Resources\Images\logout.svg" />
	  <None Remove="Resources\Images\profile.svg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="G3Software.Net.Maui.Core" Version="2.1.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.100" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.100" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.100" />
		<PackageReference Include="Plugin.Fingerprint" Version="3.0.0-beta.1" />
		<PackageReference Include="Plugin.NFC" Version="0.1.26" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Platforms\iOS\AppleInjectionSetup.cs">
	    <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
	  </Compile>
	  <Compile Update="Platforms\iOS\AppleWiFi.cs">
	    <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\BasePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Login.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
